version: 2
updates:
  - package-ecosystem: "docker"
    directories:
      - "/k8s/control-plane"
      - "/k8s/worker"
      - "/admin"
    schedule:
      interval: "monthly"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
