# First boot of a node: kubeadm configuration, then init on the control plane
# and join on every other node.
k8s = node['hpc-lab-k8s']

if ENV['K8S_TOKEN'].to_s.empty?
  raise "K8S_TOKEN is not set: #{k8s['home']}/k8s.secrets.env is k8s/.env.secrets.local, generated by `make start-k8s`"
end

execute "kubeadm is #{k8s['kubernetes_version']}" do
  command "kubeadm version -o short | grep -qxF '#{k8s['kubernetes_version']}'"
end

template '/etc/kubeadm.conf' do
  source 'kubeadm.conf.erb'
  variables(
    kubernetes_version: k8s['kubernetes_version'],
    cluster_name: k8s['cluster_name'],
    control_plane_host: k8s['control_plane_host'],
    api_port: k8s['api_port'],
    pod_subnet: k8s['pod_subnet'],
    service_subnet: k8s['service_subnet']
  )
end

# Cluster-wide scratch directory the Slurm pods mount, writable by everyone like /tmp.
directory '/shared' do
  mode '1777'
end

control_plane = node['hostname'] == k8s['control_plane_host']
include_recipe control_plane ? 'hpc-lab-k8s::control_plane' : 'hpc-lab-k8s::worker'
